# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

# Use the official PostgreSQL image as base:
FROM voxpupuli/container-puppetdb:8.3.0-latest

